---
abstract: 'An Author Distribution C<SIGNATURE> Test for L<Dist::Zilla>'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Test::DZil: '0'
  Test::Deep: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-AuthorSignatureTest
requires:
  Dist::Zilla::Plugin::InlineFiles: '0'
  Dist::Zilla::Role::PrereqSource: '0'
  Moose: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-AuthorSignatureTest
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-AuthorSignatureTest/
  repository: git://github.com/mschout/perl-dist-zilla-plugin-authorsignaturetest.git
version: '0.02'
x_serialization_backend: 'YAML::Tiny version 1.69'
